<?php

namespace Database\Seeders;

use App\Models\Municipio;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DistritoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('distrito')->insert([
            ['codigo' => '0101', 'descripcion' => 'Ahuachapán', 'municipio_id' => Municipio::where('codigo', '0101')->first()->id],
            ['codigo' => '0102', 'descripcion' => 'Apaneca', 'municipio_id' => Municipio::where('codigo', '0101')->first()->id],
            ['codigo' => '0104', 'descripcion' => 'Concepción de Ataco', 'municipio_id' => Municipio::where('codigo', '0101')->first()->id],
            ['codigo' => '0111', 'descripcion' => 'Tacuba', 'municipio_id' => Municipio::where('codigo', '0101')->first()->id],
            ['codigo' => '0103', 'descripcion' => 'Atiquizaya', 'municipio_id' => Municipio::where('codigo', '0102')->first()->id],
            ['codigo' => '0105', 'descripcion' => 'El Refugio', 'municipio_id' => Municipio::where('codigo', '0102')->first()->id],
            ['codigo' => '0109', 'descripcion' => 'San Lorenzo', 'municipio_id' => Municipio::where('codigo', '0102')->first()->id],
            ['codigo' => '0112', 'descripcion' => 'Turín', 'municipio_id' => Municipio::where('codigo', '0102')->first()->id],
            ['codigo' => '0106', 'descripcion' => 'Guaymango', 'municipio_id' => Municipio::where('codigo', '0103')->first()->id],
            ['codigo' => '0107', 'descripcion' => 'Jujutla', 'municipio_id' => Municipio::where('codigo', '0103')->first()->id],
            ['codigo' => '0108', 'descripcion' => 'San Francisco Menéndez', 'municipio_id' => Municipio::where('codigo', '0103')->first()->id],
            ['codigo' => '0110', 'descripcion' => 'San Pedro Puxtla', 'municipio_id' => Municipio::where('codigo', '0103')->first()->id],
            ['codigo' => '0210', 'descripcion' => 'Santa Ana', 'municipio_id' => Municipio::where('codigo', '0201')->first()->id],
            ['codigo' => '0202', 'descripcion' => 'Coatepeque', 'municipio_id' => Municipio::where('codigo', '0202')->first()->id],
            ['codigo' => '0204', 'descripcion' => 'El Congo', 'municipio_id' => Municipio::where('codigo', '0202')->first()->id],
            ['codigo' => '0206', 'descripcion' => 'Masahuat', 'municipio_id' => Municipio::where('codigo', '0203')->first()->id],
            ['codigo' => '0207', 'descripcion' => 'Metapán', 'municipio_id' => Municipio::where('codigo', '0203')->first()->id],
            ['codigo' => '0211', 'descripcion' => 'Santa Rosa Guachipilín', 'municipio_id' => Municipio::where('codigo', '0203')->first()->id],
            ['codigo' => '0213', 'descripcion' => 'Texistepeque', 'municipio_id' => Municipio::where('codigo', '0203')->first()->id],
            ['codigo' => '0201', 'descripcion' => 'Candelaria de la Frontera', 'municipio_id' => Municipio::where('codigo', '0204')->first()->id],
            ['codigo' => '0203', 'descripcion' => 'Chalchuapa', 'municipio_id' => Municipio::where('codigo', '0204')->first()->id],
            ['codigo' => '0205', 'descripcion' => 'El Porvenir', 'municipio_id' => Municipio::where('codigo', '0204')->first()->id],
            ['codigo' => '0208', 'descripcion' => 'San Antonio Pajonal', 'municipio_id' => Municipio::where('codigo', '0204')->first()->id],
            ['codigo' => '0209', 'descripcion' => 'San Sebastián Salitrillo', 'municipio_id' => Municipio::where('codigo', '0204')->first()->id],
            ['codigo' => '0212', 'descripcion' => 'Santiago de la Frontera', 'municipio_id' => Municipio::where('codigo', '0204')->first()->id],
            ['codigo' => '0309', 'descripcion' => 'Nahulingo', 'municipio_id' => Municipio::where('codigo', '0301')->first()->id],
            ['codigo' => '0311', 'descripcion' => 'San Antonio del Monte', 'municipio_id' => Municipio::where('codigo', '0301')->first()->id],
            ['codigo' => '0314', 'descripcion' => 'Santo Domingo de Guzmán', 'municipio_id' => Municipio::where('codigo', '0301')->first()->id],
            ['codigo' => '0315', 'descripcion' => 'Sonsonate', 'municipio_id' => Municipio::where('codigo', '0301')->first()->id],
            ['codigo' => '0316', 'descripcion' => 'Sonzacate', 'municipio_id' => Municipio::where('codigo', '0301')->first()->id],
            ['codigo' => '0302', 'descripcion' => 'Armenia', 'municipio_id' => Municipio::where('codigo', '0302')->first()->id],
            ['codigo' => '0303', 'descripcion' => 'Caluco', 'municipio_id' => Municipio::where('codigo', '0302')->first()->id],
            ['codigo' => '0304', 'descripcion' => 'Cuisnahuat', 'municipio_id' => Municipio::where('codigo', '0302')->first()->id],
            ['codigo' => '0305', 'descripcion' => 'Santa Isabel Ishuatán', 'municipio_id' => Municipio::where('codigo', '0302')->first()->id],
            ['codigo' => '0306', 'descripcion' => 'Izalco', 'municipio_id' => Municipio::where('codigo', '0302')->first()->id],
            ['codigo' => '0312', 'descripcion' => 'San Julián', 'municipio_id' => Municipio::where('codigo', '0302')->first()->id],
            ['codigo' => '0307', 'descripcion' => 'Juayúa', 'municipio_id' => Municipio::where('codigo', '0303')->first()->id],
            ['codigo' => '0308', 'descripcion' => 'Nahuizalco', 'municipio_id' => Municipio::where('codigo', '0303')->first()->id],
            ['codigo' => '0310', 'descripcion' => 'Salcoatitán', 'municipio_id' => Municipio::where('codigo', '0303')->first()->id],
            ['codigo' => '0313', 'descripcion' => 'Santa Catarina Masahuat', 'municipio_id' => Municipio::where('codigo', '0303')->first()->id],
            ['codigo' => '0301', 'descripcion' => 'Acajutla', 'municipio_id' => Municipio::where('codigo', '0304')->first()->id],
            ['codigo' => '0401', 'descripcion' => 'Agua Caliente', 'municipio_id' => Municipio::where('codigo', '0401')->first()->id],
            ['codigo' => '0408', 'descripcion' => 'Dulce Nombre de María', 'municipio_id' => Municipio::where('codigo', '0401')->first()->id],
            ['codigo' => '0410', 'descripcion' => 'El Paraíso', 'municipio_id' => Municipio::where('codigo', '0401')->first()->id],
            ['codigo' => '0413', 'descripcion' => 'La Reina', 'municipio_id' => Municipio::where('codigo', '0401')->first()->id],
            ['codigo' => '0416', 'descripcion' => 'Nueva Concepción', 'municipio_id' => Municipio::where('codigo', '0401')->first()->id],
            ['codigo' => '0422', 'descripcion' => 'San Fernando', 'municipio_id' => Municipio::where('codigo', '0401')->first()->id],
            ['codigo' => '0424', 'descripcion' => 'San Francisco Morazán', 'municipio_id' => Municipio::where('codigo', '0401')->first()->id],
            ['codigo' => '0431', 'descripcion' => 'San Rafael', 'municipio_id' => Municipio::where('codigo', '0401')->first()->id],
            ['codigo' => '0432', 'descripcion' => 'Santa Rita', 'municipio_id' => Municipio::where('codigo', '0401')->first()->id],
            ['codigo' => '0433', 'descripcion' => 'Tejutla', 'municipio_id' => Municipio::where('codigo', '0401')->first()->id],
            ['codigo' => '0404', 'descripcion' => 'Citalá', 'municipio_id' => Municipio::where('codigo', '0402')->first()->id],
            ['codigo' => '0425', 'descripcion' => 'San Ignacio', 'municipio_id' => Municipio::where('codigo', '0402')->first()->id],
            ['codigo' => '0412', 'descripcion' => 'La Palma', 'municipio_id' => Municipio::where('codigo', '0402')->first()->id],
            ['codigo' => '0402', 'descripcion' => 'Arcatao', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0403', 'descripcion' => 'Azacualpa', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0405', 'descripcion' => 'Comalapa', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0406', 'descripcion' => 'Concepción Quezaltepeque', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0407', 'descripcion' => 'Chalatenango', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0409', 'descripcion' => 'El Carrizal', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0411', 'descripcion' => 'La Laguna', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0414', 'descripcion' => 'Las Vueltas', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0415', 'descripcion' => 'Nombre de Jesús', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0417', 'descripcion' => 'Nueva Trinidad', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0418', 'descripcion' => 'Ojos de Agua', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0419', 'descripcion' => 'Potonico', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0420', 'descripcion' => 'San Antonio de la Cruz', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0421', 'descripcion' => 'San Antonio Los Ranchos', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0426', 'descripcion' => 'San Isidro Labrador', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0423', 'descripcion' => 'San Francisco Lempa', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0427', 'descripcion' => 'San José Cancasque / Cancasque', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0428', 'descripcion' => 'San José Las Flores / Las Flores', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0429', 'descripcion' => 'San Luis del Carmen', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0430', 'descripcion' => 'San Miguel de Mercedes', 'municipio_id' => Municipio::where('codigo', '0403')->first()->id],
            ['codigo' => '0502', 'descripcion' => 'Ciudad Arce', 'municipio_id' => Municipio::where('codigo', '0501')->first()->id],
            ['codigo' => '0515', 'descripcion' => 'San Juan Opico', 'municipio_id' => Municipio::where('codigo', '0501')->first()->id],
            ['codigo' => '0505', 'descripcion' => 'Chiltiupán', 'municipio_id' => Municipio::where('codigo', '0502')->first()->id],
            ['codigo' => '0508', 'descripcion' => 'Jicalapa', 'municipio_id' => Municipio::where('codigo', '0502')->first()->id],
            ['codigo' => '0509', 'descripcion' => 'La Libertad', 'municipio_id' => Municipio::where('codigo', '0502')->first()->id],
            ['codigo' => '0518', 'descripcion' => 'Tamanique', 'municipio_id' => Municipio::where('codigo', '0502')->first()->id],
            ['codigo' => '0520', 'descripcion' => 'Teotepeque', 'municipio_id' => Municipio::where('codigo', '0502')->first()->id],
            ['codigo' => '0501', 'descripcion' => 'Antiguo Cuscatlán', 'municipio_id' => Municipio::where('codigo', '0503')->first()->id],
            ['codigo' => '0506', 'descripcion' => 'Huizúcar', 'municipio_id' => Municipio::where('codigo', '0503')->first()->id],
            ['codigo' => '0510', 'descripcion' => 'Nuevo Cuscatlán', 'municipio_id' => Municipio::where('codigo', '0503')->first()->id],
            ['codigo' => '0514', 'descripcion' => 'San José Villanueva', 'municipio_id' => Municipio::where('codigo', '0503')->first()->id],
            ['codigo' => '0522', 'descripcion' => 'Zaragoza', 'municipio_id' => Municipio::where('codigo', '0503')->first()->id],
            ['codigo' => '0512', 'descripcion' => 'Quezaltepeque', 'municipio_id' => Municipio::where('codigo', '0504')->first()->id],
            ['codigo' => '0516', 'descripcion' => 'San Matías', 'municipio_id' => Municipio::where('codigo', '0504')->first()->id],
            ['codigo' => '0517', 'descripcion' => 'San Pablo Tacachico', 'municipio_id' => Municipio::where('codigo', '0504')->first()->id],
            ['codigo' => '0503', 'descripcion' => 'Colón', 'municipio_id' => Municipio::where('codigo', '0505')->first()->id],
            ['codigo' => '0507', 'descripcion' => 'Jayaque', 'municipio_id' => Municipio::where('codigo', '0505')->first()->id],
            ['codigo' => '0513', 'descripcion' => 'Sacacoyo', 'municipio_id' => Municipio::where('codigo', '0505')->first()->id],
            ['codigo' => '0519', 'descripcion' => 'Talnique', 'municipio_id' => Municipio::where('codigo', '0505')->first()->id],
            ['codigo' => '0521', 'descripcion' => 'Tepecoyo', 'municipio_id' => Municipio::where('codigo', '0505')->first()->id],
            ['codigo' => '0504', 'descripcion' => 'Comasagua', 'municipio_id' => Municipio::where('codigo', '0506')->first()->id],
            ['codigo' => '0511', 'descripcion' => 'Santa Tecla antes: Nueva San Salvador', 'municipio_id' => Municipio::where('codigo', '0506')->first()->id],
            ['codigo' => '0603', 'descripcion' => 'Ayutuxtepeque', 'municipio_id' => Municipio::where('codigo', '0601')->first()->id],
            ['codigo' => '0604', 'descripcion' => 'Cuscatancingo', 'municipio_id' => Municipio::where('codigo', '0601')->first()->id],
            ['codigo' => '0608', 'descripcion' => 'Mejicanos', 'municipio_id' => Municipio::where('codigo', '0601')->first()->id],
            ['codigo' => '0614', 'descripcion' => 'San Salvador', 'municipio_id' => Municipio::where('codigo', '0601')->first()->id],
            ['codigo' => '0619', 'descripcion' => 'Delgado', 'municipio_id' => Municipio::where('codigo', '0601')->first()->id],
            ['codigo' => '0607', 'descripcion' => 'Ilopango', 'municipio_id' => Municipio::where('codigo', '0602')->first()->id],
            ['codigo' => '0613', 'descripcion' => 'San Martín', 'municipio_id' => Municipio::where('codigo', '0602')->first()->id],
            ['codigo' => '0617', 'descripcion' => 'Soyapango', 'municipio_id' => Municipio::where('codigo', '0602')->first()->id],
            ['codigo' => '0618', 'descripcion' => 'Tonacatepeque', 'municipio_id' => Municipio::where('codigo', '0602')->first()->id],
            ['codigo' => '0601', 'descripcion' => 'Aguilares', 'municipio_id' => Municipio::where('codigo', '0603')->first()->id],
            ['codigo' => '0605', 'descripcion' => 'El Paisnal', 'municipio_id' => Municipio::where('codigo', '0603')->first()->id],
            ['codigo' => '0606', 'descripcion' => 'Guazapa', 'municipio_id' => Municipio::where('codigo', '0603')->first()->id],
            ['codigo' => '0602', 'descripcion' => 'Apopa', 'municipio_id' => Municipio::where('codigo', '0604')->first()->id],
            ['codigo' => '0609', 'descripcion' => 'Nejapa', 'municipio_id' => Municipio::where('codigo', '0604')->first()->id],
            ['codigo' => '0610', 'descripcion' => 'Panchimalco', 'municipio_id' => Municipio::where('codigo', '0605')->first()->id],
            ['codigo' => '0611', 'descripcion' => 'Rosario de Mora', 'municipio_id' => Municipio::where('codigo', '0605')->first()->id],
            ['codigo' => '0612', 'descripcion' => 'San Marcos', 'municipio_id' => Municipio::where('codigo', '0605')->first()->id],
            ['codigo' => '0615', 'descripcion' => 'Santiago Texacuangos', 'municipio_id' => Municipio::where('codigo', '0605')->first()->id],
            ['codigo' => '0616', 'descripcion' => 'Santo Tomás', 'municipio_id' => Municipio::where('codigo', '0605')->first()->id],
            ['codigo' => '0706', 'descripcion' => 'Oratorio de Concepción', 'municipio_id' => Municipio::where('codigo', '0701')->first()->id],
            ['codigo' => '0707', 'descripcion' => 'San Bartolomé Perulapía', 'municipio_id' => Municipio::where('codigo', '0701')->first()->id],
            ['codigo' => '0709', 'descripcion' => 'San José Guayabal', 'municipio_id' => Municipio::where('codigo', '0701')->first()->id],
            ['codigo' => '0710', 'descripcion' => 'San Pedro Perulapán', 'municipio_id' => Municipio::where('codigo', '0701')->first()->id],
            ['codigo' => '0715', 'descripcion' => 'Suchitoto', 'municipio_id' => Municipio::where('codigo', '0701')->first()->id],
            ['codigo' => '0701', 'descripcion' => 'Candelaria', 'municipio_id' => Municipio::where('codigo', '0702')->first()->id],
            ['codigo' => '0702', 'descripcion' => 'Cojutepeque', 'municipio_id' => Municipio::where('codigo', '0702')->first()->id],
            ['codigo' => '0703', 'descripcion' => 'El Carmen', 'municipio_id' => Municipio::where('codigo', '0702')->first()->id],
            ['codigo' => '0704', 'descripcion' => 'El Rosario', 'municipio_id' => Municipio::where('codigo', '0702')->first()->id],
            ['codigo' => '0705', 'descripcion' => 'Monte San Juan', 'municipio_id' => Municipio::where('codigo', '0702')->first()->id],
            ['codigo' => '0708', 'descripcion' => 'San Cristóbal', 'municipio_id' => Municipio::where('codigo', '0702')->first()->id],
            ['codigo' => '0711', 'descripcion' => 'San Rafael Cedros', 'municipio_id' => Municipio::where('codigo', '0702')->first()->id],
            ['codigo' => '0712', 'descripcion' => 'San Ramón', 'municipio_id' => Municipio::where('codigo', '0702')->first()->id],
            ['codigo' => '0713', 'descripcion' => 'Santa Cruz Analquito', 'municipio_id' => Municipio::where('codigo', '0702')->first()->id],
            ['codigo' => '0714', 'descripcion' => 'Santa Cruz Michapa', 'municipio_id' => Municipio::where('codigo', '0702')->first()->id],
            ['codigo' => '0716', 'descripcion' => 'Tenancingo', 'municipio_id' => Municipio::where('codigo', '0702')->first()->id],
            ['codigo' => '0802', 'descripcion' => 'El Rosario / Rosario de La Paz', 'municipio_id' => Municipio::where('codigo', '0801')->first()->id],
            ['codigo' => '0803', 'descripcion' => 'Jerusalén', 'municipio_id' => Municipio::where('codigo', '0801')->first()->id],
            ['codigo' => '0804', 'descripcion' => 'Mercedes La Ceiba', 'municipio_id' => Municipio::where('codigo', '0801')->first()->id],
            ['codigo' => '0806', 'descripcion' => 'Paraíso de Osorio', 'municipio_id' => Municipio::where('codigo', '0801')->first()->id],
            ['codigo' => '0807', 'descripcion' => 'San Antonio Masahuat', 'municipio_id' => Municipio::where('codigo', '0801')->first()->id],
            ['codigo' => '0808', 'descripcion' => 'San Emigdio', 'municipio_id' => Municipio::where('codigo', '0801')->first()->id],
            ['codigo' => '0812', 'descripcion' => 'San Juan Tepezontes', 'municipio_id' => Municipio::where('codigo', '0801')->first()->id],
            ['codigo' => '0814', 'descripcion' => 'San Miguel Tepezontes', 'municipio_id' => Municipio::where('codigo', '0801')->first()->id],
            ['codigo' => '0816', 'descripcion' => 'San Pedro Nonualco', 'municipio_id' => Municipio::where('codigo', '0801')->first()->id],
            ['codigo' => '0818', 'descripcion' => 'Santa María Ostuma', 'municipio_id' => Municipio::where('codigo', '0801')->first()->id],
            ['codigo' => '0819', 'descripcion' => 'Santiago Nonualco', 'municipio_id' => Municipio::where('codigo', '0801')->first()->id],
            ['codigo' => '0822', 'descripcion' => 'San Luis La Herradura', 'municipio_id' => Municipio::where('codigo', '0801')->first()->id],
            ['codigo' => '0810', 'descripcion' => 'San Juan Nonualco', 'municipio_id' => Municipio::where('codigo', '0802')->first()->id],
            ['codigo' => '0817', 'descripcion' => 'San Rafael Obrajuelo', 'municipio_id' => Municipio::where('codigo', '0802')->first()->id],
            ['codigo' => '0821', 'descripcion' => 'Zacatecoluca', 'municipio_id' => Municipio::where('codigo', '0802')->first()->id],
            ['codigo' => '0801', 'descripcion' => 'Cuyultitán', 'municipio_id' => Municipio::where('codigo', '0803')->first()->id],
            ['codigo' => '0805', 'descripcion' => 'Olocuilta', 'municipio_id' => Municipio::where('codigo', '0803')->first()->id],
            ['codigo' => '0809', 'descripcion' => 'San Francisco Chinameca', 'municipio_id' => Municipio::where('codigo', '0803')->first()->id],
            ['codigo' => '0811', 'descripcion' => 'San Juan Talpa', 'municipio_id' => Municipio::where('codigo', '0803')->first()->id],
            ['codigo' => '0813', 'descripcion' => 'San Luis Talpa', 'municipio_id' => Municipio::where('codigo', '0803')->first()->id],
            ['codigo' => '0815', 'descripcion' => 'San Pedro Masahuat', 'municipio_id' => Municipio::where('codigo', '0803')->first()->id],
            ['codigo' => '0820', 'descripcion' => 'Tapalhuaca', 'municipio_id' => Municipio::where('codigo', '0803')->first()->id],
            ['codigo' => '0909', 'descripcion' => 'Dolores / Villa Dolores', 'municipio_id' => Municipio::where('codigo', '0901')->first()->id],
            ['codigo' => '0902', 'descripcion' => 'Guacotecti', 'municipio_id' => Municipio::where('codigo', '0901')->first()->id],
            ['codigo' => '0905', 'descripcion' => 'San Isidro', 'municipio_id' => Municipio::where('codigo', '0901')->first()->id],
            ['codigo' => '0906', 'descripcion' => 'Sensuntepeque', 'municipio_id' => Municipio::where('codigo', '0901')->first()->id],
            ['codigo' => '0908', 'descripcion' => 'Victoria', 'municipio_id' => Municipio::where('codigo', '0901')->first()->id],
            ['codigo' => '0901', 'descripcion' => 'Cinquera', 'municipio_id' => Municipio::where('codigo', '0902')->first()->id],
            ['codigo' => '0903', 'descripcion' => 'Ilobasco', 'municipio_id' => Municipio::where('codigo', '0902')->first()->id],
            ['codigo' => '0904', 'descripcion' => 'Jutiapa', 'municipio_id' => Municipio::where('codigo', '0902')->first()->id],
            ['codigo' => '0907', 'descripcion' => 'Tejutepeque', 'municipio_id' => Municipio::where('codigo', '0902')->first()->id],
            ['codigo' => '1001', 'descripcion' => 'Apastepeque', 'municipio_id' => Municipio::where('codigo', '1001')->first()->id],
            ['codigo' => '1006', 'descripcion' => 'San Esteban Catarina', 'municipio_id' => Municipio::where('codigo', '1001')->first()->id],
            ['codigo' => '1007', 'descripcion' => 'San Ildefonso', 'municipio_id' => Municipio::where('codigo', '1001')->first()->id],
            ['codigo' => '1008', 'descripcion' => 'San Lorenzo', 'municipio_id' => Municipio::where('codigo', '1001')->first()->id],
            ['codigo' => '1009', 'descripcion' => 'San Sebastián', 'municipio_id' => Municipio::where('codigo', '1001')->first()->id],
            ['codigo' => '1004', 'descripcion' => 'Santa Clara', 'municipio_id' => Municipio::where('codigo', '1001')->first()->id],
            ['codigo' => '1005', 'descripcion' => 'Santo Domingo', 'municipio_id' => Municipio::where('codigo', '1001')->first()->id],
            ['codigo' => '1002', 'descripcion' => 'Guadalupe', 'municipio_id' => Municipio::where('codigo', '1002')->first()->id],
            ['codigo' => '1003', 'descripcion' => 'San Cayetano Istepeque', 'municipio_id' => Municipio::where('codigo', '1002')->first()->id],
            ['codigo' => '1010', 'descripcion' => 'San Vicente', 'municipio_id' => Municipio::where('codigo', '1002')->first()->id],
            ['codigo' => '1011', 'descripcion' => 'Tecoluca', 'municipio_id' => Municipio::where('codigo', '1002')->first()->id],
            ['codigo' => '1012', 'descripcion' => 'Tepetitán', 'municipio_id' => Municipio::where('codigo', '1002')->first()->id],
            ['codigo' => '1013', 'descripcion' => 'Verapaz', 'municipio_id' => Municipio::where('codigo', '1002')->first()->id],
            ['codigo' => '1103', 'descripcion' => 'California', 'municipio_id' => Municipio::where('codigo', '1101')->first()->id],
            ['codigo' => '1104', 'descripcion' => 'Concepción Batres', 'municipio_id' => Municipio::where('codigo', '1101')->first()->id],
            ['codigo' => '1106', 'descripcion' => 'Ereguayquín', 'municipio_id' => Municipio::where('codigo', '1101')->first()->id],
            ['codigo' => '1110', 'descripcion' => 'Jucuarán', 'municipio_id' => Municipio::where('codigo', '1101')->first()->id],
            ['codigo' => '1113', 'descripcion' => 'Ozatlán', 'municipio_id' => Municipio::where('codigo', '1101')->first()->id],
            ['codigo' => '1123', 'descripcion' => 'Usulután', 'municipio_id' => Municipio::where('codigo', '1101')->first()->id],
            ['codigo' => '1117', 'descripcion' => 'San Dionisio', 'municipio_id' => Municipio::where('codigo', '1101')->first()->id],
            ['codigo' => '1118', 'descripcion' => 'Santa Elena', 'municipio_id' => Municipio::where('codigo', '1101')->first()->id],
            ['codigo' => '1120', 'descripcion' => 'Santa María', 'municipio_id' => Municipio::where('codigo', '1101')->first()->id],
            ['codigo' => '1122', 'descripcion' => 'Tecapán', 'municipio_id' => Municipio::where('codigo', '1101')->first()->id],
            ['codigo' => '1101', 'descripcion' => 'Alegría', 'municipio_id' => Municipio::where('codigo', '1102')->first()->id],
            ['codigo' => '1102', 'descripcion' => 'Berlín', 'municipio_id' => Municipio::where('codigo', '1102')->first()->id],
            ['codigo' => '1105', 'descripcion' => 'El Triunfo', 'municipio_id' => Municipio::where('codigo', '1102')->first()->id],
            ['codigo' => '1107', 'descripcion' => 'Estanzuelas', 'municipio_id' => Municipio::where('codigo', '1102')->first()->id],
            ['codigo' => '1109', 'descripcion' => 'Jucuapa', 'municipio_id' => Municipio::where('codigo', '1102')->first()->id],
            ['codigo' => '1111', 'descripcion' => 'Mercedes Umaña', 'municipio_id' => Municipio::where('codigo', '1102')->first()->id],
            ['codigo' => '1112', 'descripcion' => 'Nueva Granada', 'municipio_id' => Municipio::where('codigo', '1102')->first()->id],
            ['codigo' => '1116', 'descripcion' => 'San Buenaventura', 'municipio_id' => Municipio::where('codigo', '1102')->first()->id],
            ['codigo' => '1121', 'descripcion' => 'Santiago de María', 'municipio_id' => Municipio::where('codigo', '1102')->first()->id],
            ['codigo' => '1108', 'descripcion' => 'Jiquilisco', 'municipio_id' => Municipio::where('codigo', '1103')->first()->id],
            ['codigo' => '1114', 'descripcion' => 'Puerto El Triunfo', 'municipio_id' => Municipio::where('codigo', '1103')->first()->id],
            ['codigo' => '1115', 'descripcion' => 'San Agustín', 'municipio_id' => Municipio::where('codigo', '1103')->first()->id],
            ['codigo' => '1119', 'descripcion' => 'San Francisco Javier', 'municipio_id' => Municipio::where('codigo', '1103')->first()->id],
            ['codigo' => '1203', 'descripcion' => 'Comacarán', 'municipio_id' => Municipio::where('codigo', '1201')->first()->id],
            ['codigo' => '1209', 'descripcion' => 'Moncagua', 'municipio_id' => Municipio::where('codigo', '1201')->first()->id],
            ['codigo' => '1206', 'descripcion' => 'Chirilagua', 'municipio_id' => Municipio::where('codigo', '1201')->first()->id],
            ['codigo' => '1212', 'descripcion' => 'Quelepa', 'municipio_id' => Municipio::where('codigo', '1201')->first()->id],
            ['codigo' => '1217', 'descripcion' => 'San Miguel', 'municipio_id' => Municipio::where('codigo', '1201')->first()->id],
            ['codigo' => '1220', 'descripcion' => 'Uluazapa', 'municipio_id' => Municipio::where('codigo', '1201')->first()->id],
            ['codigo' => '1201', 'descripcion' => 'Carolina', 'municipio_id' => Municipio::where('codigo', '1202')->first()->id],
            ['codigo' => '1202', 'descripcion' => 'Ciudad Barrios', 'municipio_id' => Municipio::where('codigo', '1202')->first()->id],
            ['codigo' => '1204', 'descripcion' => 'Chapeltique', 'municipio_id' => Municipio::where('codigo', '1202')->first()->id],
            ['codigo' => '1211', 'descripcion' => 'Nuevo Edén de San Juan', 'municipio_id' => Municipio::where('codigo', '1202')->first()->id],
            ['codigo' => '1213', 'descripcion' => 'San Antonio del Mosco', 'municipio_id' => Municipio::where('codigo', '1202')->first()->id],
            ['codigo' => '1214', 'descripcion' => 'San Gerardo', 'municipio_id' => Municipio::where('codigo', '1202')->first()->id],
            ['codigo' => '1216', 'descripcion' => 'San Luis de La Reina', 'municipio_id' => Municipio::where('codigo', '1202')->first()->id],
            ['codigo' => '1219', 'descripcion' => 'Sesori', 'municipio_id' => Municipio::where('codigo', '1202')->first()->id],
            ['codigo' => '1205', 'descripcion' => 'Chinameca', 'municipio_id' => Municipio::where('codigo', '1203')->first()->id],
            ['codigo' => '1207', 'descripcion' => 'El Tránsito', 'municipio_id' => Municipio::where('codigo', '1203')->first()->id],
            ['codigo' => '1208', 'descripcion' => 'Lolotique', 'municipio_id' => Municipio::where('codigo', '1203')->first()->id],
            ['codigo' => '1210', 'descripcion' => 'Nueva Guadalupe', 'municipio_id' => Municipio::where('codigo', '1203')->first()->id],
            ['codigo' => '1215', 'descripcion' => 'San Jorge', 'municipio_id' => Municipio::where('codigo', '1203')->first()->id],
            ['codigo' => '1218', 'descripcion' => 'San Rafael Oriente', 'municipio_id' => Municipio::where('codigo', '1203')->first()->id],
            ['codigo' => '1301', 'descripcion' => 'Arambala', 'municipio_id' => Municipio::where('codigo', '1301')->first()->id],
            ['codigo' => '1302', 'descripcion' => 'Cacaopera', 'municipio_id' => Municipio::where('codigo', '1301')->first()->id],
            ['codigo' => '1303', 'descripcion' => 'Corinto', 'municipio_id' => Municipio::where('codigo', '1301')->first()->id],
            ['codigo' => '1307', 'descripcion' => 'El Rosario', 'municipio_id' => Municipio::where('codigo', '1301')->first()->id],
            ['codigo' => '1310', 'descripcion' => 'Joateca', 'municipio_id' => Municipio::where('codigo', '1301')->first()->id],
            ['codigo' => '1311', 'descripcion' => 'Jocoaitique', 'municipio_id' => Municipio::where('codigo', '1301')->first()->id],
            ['codigo' => '1314', 'descripcion' => 'Meanguera', 'municipio_id' => Municipio::where('codigo', '1301')->first()->id],
            ['codigo' => '1316', 'descripcion' => 'Perquín', 'municipio_id' => Municipio::where('codigo', '1301')->first()->id],
            ['codigo' => '1318', 'descripcion' => 'San Fernando', 'municipio_id' => Municipio::where('codigo', '1301')->first()->id],
            ['codigo' => '1320', 'descripcion' => 'San Isidro', 'municipio_id' => Municipio::where('codigo', '1301')->first()->id],
            ['codigo' => '1324', 'descripcion' => 'Torola', 'municipio_id' => Municipio::where('codigo', '1301')->first()->id],
            ['codigo' => '1304', 'descripcion' => 'Chilanga', 'municipio_id' => Municipio::where('codigo', '1302')->first()->id],
            ['codigo' => '1305', 'descripcion' => 'Delicias de Concepción', 'municipio_id' => Municipio::where('codigo', '1302')->first()->id],
            ['codigo' => '1306', 'descripcion' => 'El Divisadero', 'municipio_id' => Municipio::where('codigo', '1302')->first()->id],
            ['codigo' => '1308', 'descripcion' => 'Gualococti', 'municipio_id' => Municipio::where('codigo', '1302')->first()->id],
            ['codigo' => '1309', 'descripcion' => 'Guatajiagua', 'municipio_id' => Municipio::where('codigo', '1302')->first()->id],
            ['codigo' => '1312', 'descripcion' => 'Jocoro', 'municipio_id' => Municipio::where('codigo', '1302')->first()->id],
            ['codigo' => '1313', 'descripcion' => 'Lolotiquillo', 'municipio_id' => Municipio::where('codigo', '1302')->first()->id],
            ['codigo' => '1315', 'descripcion' => 'Osicala', 'municipio_id' => Municipio::where('codigo', '1302')->first()->id],
            ['codigo' => '1317', 'descripcion' => 'San Carlos', 'municipio_id' => Municipio::where('codigo', '1302')->first()->id],
            ['codigo' => '1319', 'descripcion' => 'San Francisco Gotera', 'municipio_id' => Municipio::where('codigo', '1302')->first()->id],
            ['codigo' => '1321', 'descripcion' => 'San Simón', 'municipio_id' => Municipio::where('codigo', '1302')->first()->id],
            ['codigo' => '1322', 'descripcion' => 'Sensembra', 'municipio_id' => Municipio::where('codigo', '1302')->first()->id],
            ['codigo' => '1323', 'descripcion' => 'Sociedad', 'municipio_id' => Municipio::where('codigo', '1302')->first()->id],
            ['codigo' => '1325', 'descripcion' => 'Yamabal', 'municipio_id' => Municipio::where('codigo', '1302')->first()->id],
            ['codigo' => '1326', 'descripcion' => 'Yoloaiquín', 'municipio_id' => Municipio::where('codigo', '1302')->first()->id],
            ['codigo' => '1401', 'descripcion' => 'Anamorós', 'municipio_id' => Municipio::where('codigo', '1401')->first()->id],
            ['codigo' => '1402', 'descripcion' => 'Bolívar', 'municipio_id' => Municipio::where('codigo', '1401')->first()->id],
            ['codigo' => '1403', 'descripcion' => 'Concepción de Oriente', 'municipio_id' => Municipio::where('codigo', '1401')->first()->id],
            ['codigo' => '1406', 'descripcion' => 'El Sauce', 'municipio_id' => Municipio::where('codigo', '1401')->first()->id],
            ['codigo' => '1409', 'descripcion' => 'Lislique', 'municipio_id' => Municipio::where('codigo', '1401')->first()->id],
            ['codigo' => '1411', 'descripcion' => 'Nueva Esparta', 'municipio_id' => Municipio::where('codigo', '1401')->first()->id],
            ['codigo' => '1412', 'descripcion' => 'Pasaquina', 'municipio_id' => Municipio::where('codigo', '1401')->first()->id],
            ['codigo' => '1413', 'descripcion' => 'Polorós', 'municipio_id' => Municipio::where('codigo', '1401')->first()->id],
            ['codigo' => '1415', 'descripcion' => 'San José La Fuente', 'municipio_id' => Municipio::where('codigo', '1401')->first()->id],
            ['codigo' => '1416', 'descripcion' => 'Santa Rosa de Lima', 'municipio_id' => Municipio::where('codigo', '1401')->first()->id],
            ['codigo' => '1404', 'descripcion' => 'Conchagua', 'municipio_id' => Municipio::where('codigo', '1402')->first()->id],
            ['codigo' => '1405', 'descripcion' => 'El Carmen', 'municipio_id' => Municipio::where('codigo', '1402')->first()->id],
            ['codigo' => '1407', 'descripcion' => 'Intipucá', 'municipio_id' => Municipio::where('codigo', '1402')->first()->id],
            ['codigo' => '1408', 'descripcion' => 'La Unión', 'municipio_id' => Municipio::where('codigo', '1402')->first()->id],
            ['codigo' => '1410', 'descripcion' => 'Meanguera del Golfo', 'municipio_id' => Municipio::where('codigo', '1402')->first()->id],
            ['codigo' => '1414', 'descripcion' => 'San Alejo', 'municipio_id' => Municipio::where('codigo', '1402')->first()->id],
            ['codigo' => '1417', 'descripcion' => 'Yayantique', 'municipio_id' => Municipio::where('codigo', '1402')->first()->id],
            ['codigo' => '1418', 'descripcion' => 'Yucuaiquín', 'municipio_id' => Municipio::where('codigo', '1402')->first()->id],

        ]);
    }
}
