<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pais')->insert([
            ['nombre' => 'Afganistán', 'name' => 'Afghanistan', 'iso2' => 'AF', 'iso3' => 'AFG', 'continente' => 'Asia'],
            ['nombre' => 'Albania', 'name' => 'Albania', 'iso2' => 'AL', 'iso3' => 'ALB', 'continente' => 'Europa'],
            ['nombre' => 'Alemania', 'name' => 'Germany', 'iso2' => 'DE', 'iso3' => 'DEU', 'continente' => 'Europa'],
            ['nombre' => 'Algeria', 'name' => 'Algeria', 'iso2' => 'DZ', 'iso3' => 'DZA', 'continente' => 'África'],
            ['nombre' => 'Andorra', 'name' => 'Andorra', 'iso2' => 'AD', 'iso3' => 'AND', 'continente' => 'Europa'],
            ['nombre' => 'Angola', 'name' => 'Angola', 'iso2' => 'AO', 'iso3' => 'AGO', 'continente' => 'África'],
            ['nombre' => 'Anguila', 'name' => 'Anguilla', 'iso2' => 'AI', 'iso3' => 'AIA', 'continente' => 'América'],
            ['nombre' => 'Antártida', 'name' => 'Antarctica', 'iso2' => 'AQ', 'iso3' => 'ATA', 'continente' => 'Antártida'],
            ['nombre' => 'Antigua y Barbuda', 'name' => 'Antigua and Barbuda', 'iso2' => 'AG', 'iso3' => 'ATG', 'continente' => 'América'],
            ['nombre' => 'Antillas Neerlandesas', 'name' => 'Netherlands Antilles', 'iso2' => 'AN', 'iso3' => 'ANT', 'continente' => 'América'],
            ['nombre' => 'Arabia Saudita', 'name' => 'Saudi Arabia', 'iso2' => 'SA', 'iso3' => 'SAU', 'continente' => 'Asia'],
            ['nombre' => 'Argentina', 'name' => 'Argentina', 'iso2' => 'AR', 'iso3' => 'ARG', 'continente' => 'América'],
            ['nombre' => 'Armenia', 'name' => 'Armenia', 'iso2' => 'AM', 'iso3' => 'ARM', 'continente' => 'Asia'],
            ['nombre' => 'Aruba', 'name' => 'Aruba', 'iso2' => 'AW', 'iso3' => 'ABW', 'continente' => 'América'],
            ['nombre' => 'Australia', 'name' => 'Australia', 'iso2' => 'AU', 'iso3' => 'AUS', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Austria', 'name' => 'Austria', 'iso2' => 'AT', 'iso3' => 'AUT', 'continente' => 'Europa'],
            ['nombre' => 'Azerbayán', 'name' => 'Azerbaijan', 'iso2' => 'AZ', 'iso3' => 'AZE', 'continente' => 'Asia'],
            ['nombre' => 'Bélgica', 'name' => 'Belgium', 'iso2' => 'BE', 'iso3' => 'BEL', 'continente' => 'Europa'],
            ['nombre' => 'Bahamas', 'name' => 'Bahamas', 'iso2' => 'BS', 'iso3' => 'BHS', 'continente' => 'América'],
            ['nombre' => 'Bahrein', 'name' => 'Bahrain', 'iso2' => 'BH', 'iso3' => 'BHR', 'continente' => 'Asia'],
            ['nombre' => 'Bangladesh', 'name' => 'Bangladesh', 'iso2' => 'BD', 'iso3' => 'BGD', 'continente' => 'Asia'],
            ['nombre' => 'Barbados', 'name' => 'Barbados', 'iso2' => 'BB', 'iso3' => 'BRB', 'continente' => 'América'],
            ['nombre' => 'Belice', 'name' => 'Belize', 'iso2' => 'BZ', 'iso3' => 'BLZ', 'continente' => 'América'],
            ['nombre' => 'Benín', 'name' => 'Benin', 'iso2' => 'BJ', 'iso3' => 'BEN', 'continente' => 'África'],
            ['nombre' => 'Bhután', 'name' => 'Bhutan', 'iso2' => 'BT', 'iso3' => 'BTN', 'continente' => 'Asia'],
            ['nombre' => 'Bielorrusia', 'name' => 'Belarus', 'iso2' => 'BY', 'iso3' => 'BLR', 'continente' => 'Europa'],
            ['nombre' => 'Birmania', 'name' => 'Myanmar', 'iso2' => 'MM', 'iso3' => 'MMR', 'continente' => 'Asia'],
            ['nombre' => 'Bolivia', 'name' => 'Bolivia', 'iso2' => 'BO', 'iso3' => 'BOL', 'continente' => 'América'],
            ['nombre' => 'Bosnia y Herzegovina', 'name' => 'Bosnia and Herzegovina', 'iso2' => 'BA', 'iso3' => 'BIH', 'continente' => 'Europa'],
            ['nombre' => 'Botsuana', 'name' => 'Botswana', 'iso2' => 'BW', 'iso3' => 'BWA', 'continente' => 'África'],
            ['nombre' => 'Brasil', 'name' => 'Brazil', 'iso2' => 'BR', 'iso3' => 'BRA', 'continente' => 'América'],
            ['nombre' => 'Brunéi', 'name' => 'Brunei', 'iso2' => 'BN', 'iso3' => 'BRN', 'continente' => 'Asia'],
            ['nombre' => 'Bulgaria', 'name' => 'Bulgaria', 'iso2' => 'BG', 'iso3' => 'BGR', 'continente' => 'Europa'],
            ['nombre' => 'Burkina Faso', 'name' => 'Burkina Faso', 'iso2' => 'BF', 'iso3' => 'BFA', 'continente' => 'África'],
            ['nombre' => 'Burundi', 'name' => 'Burundi', 'iso2' => 'BI', 'iso3' => 'BDI', 'continente' => 'África'],
            ['nombre' => 'Cabo Verde', 'name' => 'Cape Verde', 'iso2' => 'CV', 'iso3' => 'CPV', 'continente' => 'África'],
            ['nombre' => 'Camboya', 'name' => 'Cambodia', 'iso2' => 'KH', 'iso3' => 'KHM', 'continente' => 'Asia'],
            ['nombre' => 'Camerún', 'name' => 'Cameroon', 'iso2' => 'CM', 'iso3' => 'CMR', 'continente' => 'África'],
            ['nombre' => 'Canadá', 'name' => 'Canada', 'iso2' => 'CA', 'iso3' => 'CAN', 'continente' => 'América'],
            ['nombre' => 'Chad', 'name' => 'Chad', 'iso2' => 'TD', 'iso3' => 'TCD', 'continente' => 'África'],
            ['nombre' => 'Chile', 'name' => 'Chile', 'iso2' => 'CL', 'iso3' => 'CHL', 'continente' => 'América'],
            ['nombre' => 'China', 'name' => 'China', 'iso2' => 'CN', 'iso3' => 'CHN', 'continente' => 'Asia'],
            ['nombre' => 'Chipre', 'name' => 'Cyprus', 'iso2' => 'CY', 'iso3' => 'CYP', 'continente' => 'Asia'],
            ['nombre' => 'Ciudad del Vaticano', 'name' => 'Vatican City State', 'iso2' => 'VA', 'iso3' => 'VAT', 'continente' => 'Europa'],
            ['nombre' => 'Colombia', 'name' => 'Colombia', 'iso2' => 'CO', 'iso3' => 'COL', 'continente' => 'América'],
            ['nombre' => 'Comoras', 'name' => 'Comoros', 'iso2' => 'KM', 'iso3' => 'COM', 'continente' => 'África'],
            ['nombre' => 'Congo', 'name' => 'Congo', 'iso2' => 'CG', 'iso3' => 'COG', 'continente' => 'África'],
            ['nombre' => 'Congo', 'name' => 'Congo', 'iso2' => 'CD', 'iso3' => 'COD', 'continente' => 'África'],
            ['nombre' => 'Corea del Norte', 'name' => 'North Korea', 'iso2' => 'KP', 'iso3' => 'PRK', 'continente' => 'Asia'],
            ['nombre' => 'Corea del Sur', 'name' => 'South Korea', 'iso2' => 'KR', 'iso3' => 'KOR', 'continente' => 'Asia'],
            ['nombre' => 'Costa de Marfil', 'name' => 'Ivory Coast', 'iso2' => 'CI', 'iso3' => 'CIV', 'continente' => 'África'],
            ['nombre' => 'Costa Rica', 'name' => 'Costa Rica', 'iso2' => 'CR', 'iso3' => 'CRI', 'continente' => 'América'],
            ['nombre' => 'Croacia', 'name' => 'Croatia', 'iso2' => 'HR', 'iso3' => 'HRV', 'continente' => 'Europa'],
            ['nombre' => 'Cuba', 'name' => 'Cuba', 'iso2' => 'CU', 'iso3' => 'CUB', 'continente' => 'América'],
            ['nombre' => 'Dinamarca', 'name' => 'Denmark', 'iso2' => 'DK', 'iso3' => 'DNK', 'continente' => 'Europa'],
            ['nombre' => 'Dominica', 'name' => 'Dominica', 'iso2' => 'DM', 'iso3' => 'DMA', 'continente' => 'América'],
            ['nombre' => 'Ecuador', 'name' => 'Ecuador', 'iso2' => 'EC', 'iso3' => 'ECU', 'continente' => 'América'],
            ['nombre' => 'Egipto', 'name' => 'Egypt', 'iso2' => 'EG', 'iso3' => 'EGY', 'continente' => 'África'],
            ['nombre' => 'El Salvador', 'name' => 'El Salvador', 'iso2' => 'SV', 'iso3' => 'SLV', 'continente' => 'América'],
            ['nombre' => 'Emiratos Árabes Unidos', 'name' => 'United Arab Emirates', 'iso2' => 'AE', 'iso3' => 'ARE', 'continente' => 'Asia'],
            ['nombre' => 'Eritrea', 'name' => 'Eritrea', 'iso2' => 'ER', 'iso3' => 'ERI', 'continente' => 'África'],
            ['nombre' => 'Eslovaquia', 'name' => 'Slovakia', 'iso2' => 'SK', 'iso3' => 'SVK', 'continente' => 'Europa'],
            ['nombre' => 'Eslovenia', 'name' => 'Slovenia', 'iso2' => 'SI', 'iso3' => 'SVN', 'continente' => 'Europa'],
            ['nombre' => 'España', 'name' => 'Spain', 'iso2' => 'ES', 'iso3' => 'ESP', 'continente' => 'Europa'],
            ['nombre' => 'Estados Unidos de América', 'name' => 'United States of America', 'iso2' => 'US', 'iso3' => 'USA', 'continente' => 'América'],
            ['nombre' => 'Estonia', 'name' => 'Estonia', 'iso2' => 'EE', 'iso3' => 'EST', 'continente' => 'Europa'],
            ['nombre' => 'Etiopía', 'name' => 'Ethiopia', 'iso2' => 'ET', 'iso3' => 'ETH', 'continente' => 'África'],
            ['nombre' => 'Filipinas', 'name' => 'Philippines', 'iso2' => 'PH', 'iso3' => 'PHL', 'continente' => 'Asia'],
            ['nombre' => 'Finlandia', 'name' => 'Finland', 'iso2' => 'FI', 'iso3' => 'FIN', 'continente' => 'Europa'],
            ['nombre' => 'Fiyi', 'name' => 'Fiji', 'iso2' => 'FJ', 'iso3' => 'FJI', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Francia', 'name' => 'France', 'iso2' => 'FR', 'iso3' => 'FRA', 'continente' => 'Europa'],
            ['nombre' => 'Gabón', 'name' => 'Gabon', 'iso2' => 'GA', 'iso3' => 'GAB', 'continente' => 'África'],
            ['nombre' => 'Gambia', 'name' => 'Gambia', 'iso2' => 'GM', 'iso3' => 'GMB', 'continente' => 'África'],
            ['nombre' => 'Georgia', 'name' => 'Georgia', 'iso2' => 'GE', 'iso3' => 'GEO', 'continente' => 'Asia'],
            ['nombre' => 'Ghana', 'name' => 'Ghana', 'iso2' => 'GH', 'iso3' => 'GHA', 'continente' => 'África'],
            ['nombre' => 'Gibraltar', 'name' => 'Gibraltar', 'iso2' => 'GI', 'iso3' => 'GIB', 'continente' => 'Europa'],
            ['nombre' => 'Granada', 'name' => 'Grenada', 'iso2' => 'GD', 'iso3' => 'GRD', 'continente' => 'América'],
            ['nombre' => 'Grecia', 'name' => 'Greece', 'iso2' => 'GR', 'iso3' => 'GRC', 'continente' => 'Europa'],
            ['nombre' => 'Groenlandia', 'name' => 'Greenland', 'iso2' => 'GL', 'iso3' => 'GRL', 'continente' => 'América'],
            ['nombre' => 'Guadalupe', 'name' => 'Guadeloupe', 'iso2' => 'GP', 'iso3' => 'GLP', 'continente' => 'América'],
            ['nombre' => 'Guam', 'name' => 'Guam', 'iso2' => 'GU', 'iso3' => 'GUM', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Guatemala', 'name' => 'Guatemala', 'iso2' => 'GT', 'iso3' => 'GTM', 'continente' => 'América'],
            ['nombre' => 'Guayana Francesa', 'name' => 'French Guiana', 'iso2' => 'GF', 'iso3' => 'GUF', 'continente' => 'América'],
            ['nombre' => 'Guernsey', 'name' => 'Guernsey', 'iso2' => 'GG', 'iso3' => 'GGY', 'continente' => 'Europa'],
            ['nombre' => 'Guinea', 'name' => 'Guinea', 'iso2' => 'GN', 'iso3' => 'GIN', 'continente' => 'África'],
            ['nombre' => 'Guinea Ecuatorial', 'name' => 'Equatorial Guinea', 'iso2' => 'GQ', 'iso3' => 'GNQ', 'continente' => 'África'],
            ['nombre' => 'Guinea-Bissau', 'name' => 'Guinea-Bissau', 'iso2' => 'GW', 'iso3' => 'GNB', 'continente' => 'África'],
            ['nombre' => 'Guyana', 'name' => 'Guyana', 'iso2' => 'GY', 'iso3' => 'GUY', 'continente' => 'América'],
            ['nombre' => 'Haití', 'name' => 'Haiti', 'iso2' => 'HT', 'iso3' => 'HTI', 'continente' => 'América'],
            ['nombre' => 'Honduras', 'name' => 'Honduras', 'iso2' => 'HN', 'iso3' => 'HND', 'continente' => 'América'],
            ['nombre' => 'Hong kong', 'name' => 'Hong Kong', 'iso2' => 'HK', 'iso3' => 'HKG', 'continente' => 'Asia'],
            ['nombre' => 'Hungría', 'name' => 'Hungary', 'iso2' => 'HU', 'iso3' => 'HUN', 'continente' => 'Europa'],
            ['nombre' => 'India', 'name' => 'India', 'iso2' => 'IN', 'iso3' => 'IND', 'continente' => 'Asia'],
            ['nombre' => 'Indonesia', 'name' => 'Indonesia', 'iso2' => 'ID', 'iso3' => 'IDN', 'continente' => 'Asia'],
            ['nombre' => 'Irán', 'name' => 'Iran', 'iso2' => 'IR', 'iso3' => 'IRN', 'continente' => 'Asia'],
            ['nombre' => 'Irak', 'name' => 'Iraq', 'iso2' => 'IQ', 'iso3' => 'IRQ', 'continente' => 'Asia'],
            ['nombre' => 'Irlanda', 'name' => 'Ireland', 'iso2' => 'IE', 'iso3' => 'IRL', 'continente' => 'Europa'],
            ['nombre' => 'Isla Bouvet', 'name' => 'Bouvet Island', 'iso2' => 'BV', 'iso3' => 'BVT', 'continente' => 'Antártida'],
            ['nombre' => 'Isla de Man', 'name' => 'Isle of Man', 'iso2' => 'IM', 'iso3' => 'IMN', 'continente' => 'Europa'],
            ['nombre' => 'Isla de Navidad', 'name' => 'Christmas Island', 'iso2' => 'CX', 'iso3' => 'CXR', 'continente' => 'Asia'],
            ['nombre' => 'Isla Norfolk', 'name' => 'Norfolk Island', 'iso2' => 'NF', 'iso3' => 'NFK', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Islandia', 'name' => 'Iceland', 'iso2' => 'IS', 'iso3' => 'ISL', 'continente' => 'Europa'],
            ['nombre' => 'Islas Bermudas', 'name' => 'Bermuda Islands', 'iso2' => 'BM', 'iso3' => 'BMU', 'continente' => 'América'],
            ['nombre' => 'Islas Caimán', 'name' => 'Cayman Islands', 'iso2' => 'KY', 'iso3' => 'CYM', 'continente' => 'América'],
            ['nombre' => 'Islas Cocos (Keeling)', 'name' => 'Cocos (Keeling) Islands', 'iso2' => 'CC', 'iso3' => 'CCK', 'continente' => 'Asia'],
            ['nombre' => 'Islas Cook', 'name' => 'Cook Islands', 'iso2' => 'CK', 'iso3' => 'COK', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Islas de Åland', 'name' => 'Åland Islands', 'iso2' => 'AX', 'iso3' => 'ALA', 'continente' => 'Europa'],
            ['nombre' => 'Islas Feroe', 'name' => 'Faroe Islands', 'iso2' => 'FO', 'iso3' => 'FRO', 'continente' => 'Europa'],
            ['nombre' => 'Islas Georgias del Sur y Sandwich del Sur', 'name' => 'South Georgia and the South Sandwich Islands', 'iso2' => 'GS', 'iso3' => 'SGS', 'continente' => 'América'],
            ['nombre' => 'Islas Heard y McDonald', 'name' => 'Heard Island and McDonald Islands', 'iso2' => 'HM', 'iso3' => 'HMD', 'continente' => 'Antártida'],
            ['nombre' => 'Islas Maldivas', 'name' => 'Maldives', 'iso2' => 'MV', 'iso3' => 'MDV', 'continente' => 'Asia'],
            ['nombre' => 'Islas Malvinas', 'name' => 'Falkland Islands (Malvinas)', 'iso2' => 'FK', 'iso3' => 'FLK', 'continente' => 'América'],
            ['nombre' => 'Islas Marianas del Norte', 'name' => 'Northern Mariana Islands', 'iso2' => 'MP', 'iso3' => 'MNP', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Islas Marshall', 'name' => 'Marshall Islands', 'iso2' => 'MH', 'iso3' => 'MHL', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Islas Pitcairn', 'name' => 'Pitcairn Islands', 'iso2' => 'PN', 'iso3' => 'PCN', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Islas Salomón', 'name' => 'Solomon Islands', 'iso2' => 'SB', 'iso3' => 'SLB', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Islas Turcas y Caicos', 'name' => 'Turks and Caicos Islands', 'iso2' => 'TC', 'iso3' => 'TCA', 'continente' => 'América'],
            ['nombre' => 'Islas Ultramarinas Menores de Estados Unidos', 'name' => 'United States Minor Outlying Islands', 'iso2' => 'UM', 'iso3' => 'UMI', 'continente' => ''],
            ['nombre' => 'Islas Vírgenes Británicas', 'name' => 'Virgin Islands', 'iso2' => 'VG', 'iso3' => 'VG', 'continente' => 'América'],
            ['nombre' => 'Islas Vírgenes de los Estados Unidos', 'name' => 'United States Virgin Islands', 'iso2' => 'VI', 'iso3' => 'VIR', 'continente' => 'América'],
            ['nombre' => 'Israel', 'name' => 'Israel', 'iso2' => 'IL', 'iso3' => 'ISR', 'continente' => 'Asia'],
            ['nombre' => 'Italia', 'name' => 'Italy', 'iso2' => 'IT', 'iso3' => 'ITA', 'continente' => 'Europa'],
            ['nombre' => 'Jamaica', 'name' => 'Jamaica', 'iso2' => 'JM', 'iso3' => 'JAM', 'continente' => 'América'],
            ['nombre' => 'Japón', 'name' => 'Japan', 'iso2' => 'JP', 'iso3' => 'JPN', 'continente' => 'Asia'],
            ['nombre' => 'Jersey', 'name' => 'Jersey', 'iso2' => 'JE', 'iso3' => 'JEY', 'continente' => 'Europa'],
            ['nombre' => 'Jordania', 'name' => 'Jordan', 'iso2' => 'JO', 'iso3' => 'JOR', 'continente' => 'Asia'],
            ['nombre' => 'Kazajistán', 'name' => 'Kazakhstan', 'iso2' => 'KZ', 'iso3' => 'KAZ', 'continente' => 'Asia'],
            ['nombre' => 'Kenia', 'name' => 'Kenya', 'iso2' => 'KE', 'iso3' => 'KEN', 'continente' => 'África'],
            ['nombre' => 'Kirgizstán', 'name' => 'Kyrgyzstan', 'iso2' => 'KG', 'iso3' => 'KGZ', 'continente' => 'Asia'],
            ['nombre' => 'Kiribati', 'name' => 'Kiribati', 'iso2' => 'KI', 'iso3' => 'KIR', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Kuwait', 'name' => 'Kuwait', 'iso2' => 'KW', 'iso3' => 'KWT', 'continente' => 'Asia'],
            ['nombre' => 'Líbano', 'name' => 'Lebanon', 'iso2' => 'LB', 'iso3' => 'LBN', 'continente' => 'Asia'],
            ['nombre' => 'Laos', 'name' => 'Laos', 'iso2' => 'LA', 'iso3' => 'LAO', 'continente' => 'Asia'],
            ['nombre' => 'Lesoto', 'name' => 'Lesotho', 'iso2' => 'LS', 'iso3' => 'LSO', 'continente' => 'África'],
            ['nombre' => 'Letonia', 'name' => 'Latvia', 'iso2' => 'LV', 'iso3' => 'LVA', 'continente' => 'Europa'],
            ['nombre' => 'Liberia', 'name' => 'Liberia', 'iso2' => 'LR', 'iso3' => 'LBR', 'continente' => 'África'],
            ['nombre' => 'Libia', 'name' => 'Libya', 'iso2' => 'LY', 'iso3' => 'LBY', 'continente' => 'África'],
            ['nombre' => 'Liechtenstein', 'name' => 'Liechtenstein', 'iso2' => 'LI', 'iso3' => 'LIE', 'continente' => 'Europa'],
            ['nombre' => 'Lituania', 'name' => 'Lithuania', 'iso2' => 'LT', 'iso3' => 'LTU', 'continente' => 'Europa'],
            ['nombre' => 'Luxemburgo', 'name' => 'Luxembourg', 'iso2' => 'LU', 'iso3' => 'LUX', 'continente' => 'Europa'],
            ['nombre' => 'México', 'name' => 'Mexico', 'iso2' => 'MX', 'iso3' => 'MEX', 'continente' => 'América'],
            ['nombre' => 'Mónaco', 'name' => 'Monaco', 'iso2' => 'MC', 'iso3' => 'MCO', 'continente' => 'Europa'],
            ['nombre' => 'Macao', 'name' => 'Macao', 'iso2' => 'MO', 'iso3' => 'MAC', 'continente' => 'Asia'],
            ['nombre' => 'Macedônia', 'name' => 'Macedonia', 'iso2' => 'MK', 'iso3' => 'MKD', 'continente' => 'Europa'],
            ['nombre' => 'Madagascar', 'name' => 'Madagascar', 'iso2' => 'MG', 'iso3' => 'MDG', 'continente' => 'África'],
            ['nombre' => 'Malasia', 'name' => 'Malaysia', 'iso2' => 'MY', 'iso3' => 'MYS', 'continente' => 'Asia'],
            ['nombre' => 'Malawi', 'name' => 'Malawi', 'iso2' => 'MW', 'iso3' => 'MWI', 'continente' => 'África'],
            ['nombre' => 'Mali', 'name' => 'Mali', 'iso2' => 'ML', 'iso3' => 'MLI', 'continente' => 'África'],
            ['nombre' => 'Malta', 'name' => 'Malta', 'iso2' => 'MT', 'iso3' => 'MLT', 'continente' => 'Europa'],
            ['nombre' => 'Marruecos', 'name' => 'Morocco', 'iso2' => 'MA', 'iso3' => 'MAR', 'continente' => 'África'],
            ['nombre' => 'Martinica', 'name' => 'Martinique', 'iso2' => 'MQ', 'iso3' => 'MTQ', 'continente' => 'América'],
            ['nombre' => 'Mauricio', 'name' => 'Mauritius', 'iso2' => 'MU', 'iso3' => 'MUS', 'continente' => 'África'],
            ['nombre' => 'Mauritania', 'name' => 'Mauritania', 'iso2' => 'MR', 'iso3' => 'MRT', 'continente' => 'África'],
            ['nombre' => 'Mayotte', 'name' => 'Mayotte', 'iso2' => 'YT', 'iso3' => 'MYT', 'continente' => 'África'],
            ['nombre' => 'Micronesia', 'name' => 'Estados Federados de', 'iso2' => 'FM', 'iso3' => 'FSM', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Moldavia', 'name' => 'Moldova', 'iso2' => 'MD', 'iso3' => 'MDA', 'continente' => 'Europa'],
            ['nombre' => 'Mongolia', 'name' => 'Mongolia', 'iso2' => 'MN', 'iso3' => 'MNG', 'continente' => 'Asia'],
            ['nombre' => 'Montenegro', 'name' => 'Montenegro', 'iso2' => 'ME', 'iso3' => 'MNE', 'continente' => 'Europa'],
            ['nombre' => 'Montserrat', 'name' => 'Montserrat', 'iso2' => 'MS', 'iso3' => 'MSR', 'continente' => 'América'],
            ['nombre' => 'Mozambique', 'name' => 'Mozambique', 'iso2' => 'MZ', 'iso3' => 'MOZ', 'continente' => 'África'],
            ['nombre' => 'Namibia', 'name' => 'Namibia', 'iso2' => 'NA', 'iso3' => 'NAM', 'continente' => 'África'],
            ['nombre' => 'Nauru', 'name' => 'Nauru', 'iso2' => 'NR', 'iso3' => 'NRU', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Nepal', 'name' => 'Nepal', 'iso2' => 'NP', 'iso3' => 'NPL', 'continente' => 'Asia'],
            ['nombre' => 'Nicaragua', 'name' => 'Nicaragua', 'iso2' => 'NI', 'iso3' => 'NIC', 'continente' => 'América'],
            ['nombre' => 'Niger', 'name' => 'Niger', 'iso2' => 'NE', 'iso3' => 'NER', 'continente' => 'África'],
            ['nombre' => 'Nigeria', 'name' => 'Nigeria', 'iso2' => 'NG', 'iso3' => 'NGA', 'continente' => 'África'],
            ['nombre' => 'Niue', 'name' => 'Niue', 'iso2' => 'NU', 'iso3' => 'NIU', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Noruega', 'name' => 'Norway', 'iso2' => 'NO', 'iso3' => 'NOR', 'continente' => 'Europa'],
            ['nombre' => 'Nueva Caledonia', 'name' => 'New Caledonia', 'iso2' => 'NC', 'iso3' => 'NCL', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Nueva Zelanda', 'name' => 'New Zealand', 'iso2' => 'NZ', 'iso3' => 'NZL', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Omán', 'name' => 'Oman', 'iso2' => 'OM', 'iso3' => 'OMN', 'continente' => 'Asia'],
            ['nombre' => 'Países Bajos', 'name' => 'Netherlands', 'iso2' => 'NL', 'iso3' => 'NLD', 'continente' => 'Europa'],
            ['nombre' => 'Pakistán', 'name' => 'Pakistan', 'iso2' => 'PK', 'iso3' => 'PAK', 'continente' => 'Asia'],
            ['nombre' => 'Palau', 'name' => 'Palau', 'iso2' => 'PW', 'iso3' => 'PLW', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Palestina', 'name' => 'Palestine', 'iso2' => 'PS', 'iso3' => 'PSE', 'continente' => 'Asia'],
            ['nombre' => 'Panamá', 'name' => 'Panama', 'iso2' => 'PA', 'iso3' => 'PAN', 'continente' => 'América'],
            ['nombre' => 'Papúa Nueva Guinea', 'name' => 'Papua New Guinea', 'iso2' => 'PG', 'iso3' => 'PNG', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Paraguay', 'name' => 'Paraguay', 'iso2' => 'PY', 'iso3' => 'PRY', 'continente' => 'América'],
            ['nombre' => 'Perú', 'name' => 'Peru', 'iso2' => 'PE', 'iso3' => 'PER', 'continente' => 'América'],
            ['nombre' => 'Polinesia Francesa', 'name' => 'French Polynesia', 'iso2' => 'PF', 'iso3' => 'PYF', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Polonia', 'name' => 'Poland', 'iso2' => 'PL', 'iso3' => 'POL', 'continente' => 'Europa'],
            ['nombre' => 'Portugal', 'name' => 'Portugal', 'iso2' => 'PT', 'iso3' => 'PRT', 'continente' => 'Europa'],
            ['nombre' => 'Puerto Rico', 'name' => 'Puerto Rico', 'iso2' => 'PR', 'iso3' => 'PRI', 'continente' => 'América'],
            ['nombre' => 'Qatar', 'name' => 'Qatar', 'iso2' => 'QA', 'iso3' => 'QAT', 'continente' => 'Asia'],
            ['nombre' => 'Reino Unido', 'name' => 'United Kingdom', 'iso2' => 'GB', 'iso3' => 'GBR', 'continente' => 'Europa'],
            ['nombre' => 'República Centroafricana', 'name' => 'Central African Republic', 'iso2' => 'CF', 'iso3' => 'CAF', 'continente' => 'África'],
            ['nombre' => 'República Checa', 'name' => 'Czech Republic', 'iso2' => 'CZ', 'iso3' => 'CZE', 'continente' => 'Europa'],
            ['nombre' => 'República Dominicana', 'name' => 'Dominican Republic', 'iso2' => 'DO', 'iso3' => 'DOM', 'continente' => 'América'],
            ['nombre' => 'Reunión', 'name' => 'Réunion', 'iso2' => 'RE', 'iso3' => 'REU', 'continente' => 'África'],
            ['nombre' => 'Ruanda', 'name' => 'Rwanda', 'iso2' => 'RW', 'iso3' => 'RWA', 'continente' => 'África'],
            ['nombre' => 'Rumanía', 'name' => 'Romania', 'iso2' => 'RO', 'iso3' => 'ROU', 'continente' => 'Europa'],
            ['nombre' => 'Rusia', 'name' => 'Russia', 'iso2' => 'RU', 'iso3' => 'RUS', 'continente' => 'Europa'],
            ['nombre' => 'Sahara Occidental', 'name' => 'Western Sahara', 'iso2' => 'EH', 'iso3' => 'ESH', 'continente' => 'África'],
            ['nombre' => 'Samoa', 'name' => 'Samoa', 'iso2' => 'WS', 'iso3' => 'WSM', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Samoa Americana', 'name' => 'American Samoa', 'iso2' => 'AS', 'iso3' => 'ASM', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'San Bartolomé', 'name' => 'Saint Barthélemy', 'iso2' => 'BL', 'iso3' => 'BLM', 'continente' => 'América'],
            ['nombre' => 'San Cristóbal y Nieves', 'name' => 'Saint Kitts and Nevis', 'iso2' => 'KN', 'iso3' => 'KNA', 'continente' => 'América'],
            ['nombre' => 'San Marino', 'name' => 'San Marino', 'iso2' => 'SM', 'iso3' => 'SMR', 'continente' => 'Europa'],
            ['nombre' => 'San Martín (Francia)', 'name' => 'Saint Martin (French part)', 'iso2' => 'MF', 'iso3' => 'MAF', 'continente' => 'América'],
            ['nombre' => 'San Pedro y Miquelón', 'name' => 'Saint Pierre and Miquelon', 'iso2' => 'PM', 'iso3' => 'SPM', 'continente' => 'América'],
            ['nombre' => 'San Vicente y las Granadinas', 'name' => 'Saint Vincent and the Grenadines', 'iso2' => 'VC', 'iso3' => 'VCT', 'continente' => 'América'],
            ['nombre' => 'Santa Elena', 'name' => 'Ascensión y Tristán de Acuña', 'iso2' => 'SH', 'iso3' => 'SHN', 'continente' => 'África'],
            ['nombre' => 'Santa Lucía', 'name' => 'Saint Lucia', 'iso2' => 'LC', 'iso3' => 'LCA', 'continente' => 'América'],
            ['nombre' => 'Santo Tomé y Príncipe', 'name' => 'Sao Tome and Principe', 'iso2' => 'ST', 'iso3' => 'STP', 'continente' => 'África'],
            ['nombre' => 'Senegal', 'name' => 'Senegal', 'iso2' => 'SN', 'iso3' => 'SEN', 'continente' => 'África'],
            ['nombre' => 'Serbia', 'name' => 'Serbia', 'iso2' => 'RS', 'iso3' => 'SRB', 'continente' => 'Europa'],
            ['nombre' => 'Seychelles', 'name' => 'Seychelles', 'iso2' => 'SC', 'iso3' => 'SYC', 'continente' => 'África'],
            ['nombre' => 'Sierra Leona', 'name' => 'Sierra Leone', 'iso2' => 'SL', 'iso3' => 'SLE', 'continente' => 'África'],
            ['nombre' => 'Singapur', 'name' => 'Singapore', 'iso2' => 'SG', 'iso3' => 'SGP', 'continente' => 'Asia'],
            ['nombre' => 'Siria', 'name' => 'Syria', 'iso2' => 'SY', 'iso3' => 'SYR', 'continente' => 'Asia'],
            ['nombre' => 'Somalia', 'name' => 'Somalia', 'iso2' => 'SO', 'iso3' => 'SOM', 'continente' => 'África'],
            ['nombre' => 'Sri lanka', 'name' => 'Sri Lanka', 'iso2' => 'LK', 'iso3' => 'LKA', 'continente' => 'Asia'],
            ['nombre' => 'Sudáfrica', 'name' => 'South Africa', 'iso2' => 'ZA', 'iso3' => 'ZAF', 'continente' => 'África'],
            ['nombre' => 'Sudán', 'name' => 'Sudan', 'iso2' => 'SD', 'iso3' => 'SDN', 'continente' => 'África'],
            ['nombre' => 'Suecia', 'name' => 'Sweden', 'iso2' => 'SE', 'iso3' => 'SWE', 'continente' => 'Europa'],
            ['nombre' => 'Suiza', 'name' => 'Switzerland', 'iso2' => 'CH', 'iso3' => 'CHE', 'continente' => 'Europa'],
            ['nombre' => 'Surinám', 'name' => 'Suriname', 'iso2' => 'SR', 'iso3' => 'SUR', 'continente' => 'América'],
            ['nombre' => 'Svalbard y Jan Mayen', 'name' => 'Svalbard and Jan Mayen', 'iso2' => 'SJ', 'iso3' => 'SJM', 'continente' => 'Europa'],
            ['nombre' => 'Swazilandia', 'name' => 'Swaziland', 'iso2' => 'SZ', 'iso3' => 'SWZ', 'continente' => 'África'],
            ['nombre' => 'Tadjikistán', 'name' => 'Tajikistan', 'iso2' => 'TJ', 'iso3' => 'TJK', 'continente' => 'Asia'],
            ['nombre' => 'Tailandia', 'name' => 'Thailand', 'iso2' => 'TH', 'iso3' => 'THA', 'continente' => 'Asia'],
            ['nombre' => 'Taiwán', 'name' => 'Taiwan', 'iso2' => 'TW', 'iso3' => 'TWN', 'continente' => 'Asia'],
            ['nombre' => 'Tanzania', 'name' => 'Tanzania', 'iso2' => 'TZ', 'iso3' => 'TZA', 'continente' => 'África'],
            ['nombre' => 'Territorio Británico del Océano Índico', 'name' => 'British Indian Ocean Territory', 'iso2' => 'IO', 'iso3' => 'IOT', 'continente' => ''],
            ['nombre' => 'Territorios Australes y Antárticas Franceses', 'name' => 'French Southern Territories', 'iso2' => 'TF', 'iso3' => 'ATF', 'continente' => ''],
            ['nombre' => 'Timor Oriental', 'name' => 'East Timor', 'iso2' => 'TL', 'iso3' => 'TLS', 'continente' => 'Asia'],
            ['nombre' => 'Togo', 'name' => 'Togo', 'iso2' => 'TG', 'iso3' => 'TGO', 'continente' => 'África'],
            ['nombre' => 'Tokelau', 'name' => 'Tokelau', 'iso2' => 'TK', 'iso3' => 'TKL', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Tonga', 'name' => 'Tonga', 'iso2' => 'TO', 'iso3' => 'TON', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Trinidad y Tobago', 'name' => 'Trinidad and Tobago', 'iso2' => 'TT', 'iso3' => 'TTO', 'continente' => 'América'],
            ['nombre' => 'Tunez', 'name' => 'Tunisia', 'iso2' => 'TN', 'iso3' => 'TUN', 'continente' => 'África'],
            ['nombre' => 'Turkmenistán', 'name' => 'Turkmenistan', 'iso2' => 'TM', 'iso3' => 'TKM', 'continente' => 'Asia'],
            ['nombre' => 'Turquía', 'name' => 'Turkey', 'iso2' => 'TR', 'iso3' => 'TUR', 'continente' => 'Asia'],
            ['nombre' => 'Tuvalu', 'name' => 'Tuvalu', 'iso2' => 'TV', 'iso3' => 'TUV', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Ucrania', 'name' => 'Ukraine', 'iso2' => 'UA', 'iso3' => 'UKR', 'continente' => 'Europa'],
            ['nombre' => 'Uganda', 'name' => 'Uganda', 'iso2' => 'UG', 'iso3' => 'UGA', 'continente' => 'África'],
            ['nombre' => 'Uruguay', 'name' => 'Uruguay', 'iso2' => 'UY', 'iso3' => 'URY', 'continente' => 'América'],
            ['nombre' => 'Uzbekistán', 'name' => 'Uzbekistan', 'iso2' => 'UZ', 'iso3' => 'UZB', 'continente' => 'Asia'],
            ['nombre' => 'Vanuatu', 'name' => 'Vanuatu', 'iso2' => 'VU', 'iso3' => 'VUT', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Venezuela', 'name' => 'Venezuela', 'iso2' => 'VE', 'iso3' => 'VEN', 'continente' => 'América'],
            ['nombre' => 'Vietnam', 'name' => 'Vietnam', 'iso2' => 'VN', 'iso3' => 'VNM', 'continente' => 'Asia'],
            ['nombre' => 'Wallis y Futuna', 'name' => 'Wallis and Futuna', 'iso2' => 'WF', 'iso3' => 'WLF', 'continente' => 'Australia y Oceanía'],
            ['nombre' => 'Yemen', 'name' => 'Yemen', 'iso2' => 'YE', 'iso3' => 'YEM', 'continente' => 'Asia'],
            ['nombre' => 'Yibuti', 'name' => 'Djibouti', 'iso2' => 'DJ', 'iso3' => 'DJI', 'continente' => 'África'],
            ['nombre' => 'Zambia', 'name' => 'Zambia', 'iso2' => 'ZM', 'iso3' => 'ZMB', 'continente' => 'África'],
            ['nombre' => 'Zimbabue', 'name' => 'Zimbabwe', 'iso2' => 'ZW', 'iso3' => 'ZWE', 'continente' => 'África'],
        ]);
    }
}
