<?php

namespace Database\Seeders\Academico;

use App\Models\Academica\Sede;
use App\Models\PlanEstudio\Carrera;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarreraSedeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('academico.carrera_sede')->insert([
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'BTC')->first()->id],

            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-S')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-CR')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-MP')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-C4')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-C3')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-SF')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-BD')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-RI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-PA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR-GH')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR-GA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-CE')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-FH')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-CA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-LA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-AN')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'NE-MK')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TEC-CON')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'NE-FD')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SS')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TEC-PL')->first()->id],

            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'BTC')->first()->id],

            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-S')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-CR')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-MP')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-C4')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-C3')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-SF')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-BD')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-RI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-PA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR-GH')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR-GA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-CE')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-FH')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-CA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-LA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-AN')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'NE-MK')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TEC-CON')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'NE-FD')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-SO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TEC-PL')->first()->id],

            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'BTC')->first()->id],

            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-S')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-CR')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-MP')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-C4')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-C3')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-SF')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-BD')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-RI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-PA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR-GH')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR-GA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-CE')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-FH')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-CA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-LA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-AN')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'NE-MK')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TEC-CON')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'NE-FD')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-CH')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TEC-PL')->first()->id],

            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'BTC')->first()->id],

            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-S')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-CR')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-MP')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-C4')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-C3')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-SF')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-BD')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-RI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-PA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR-GH')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR-GA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-CE')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-FH')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-CA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-LA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-AN')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'NE-MK')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TEC-CON')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'NE-FD')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-ZA')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TEC-PL')->first()->id],

            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'BTC')->first()->id],

            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-S')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-CR')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-MP')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-C4')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-C3')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-SF')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-BD')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-RI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-PA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR-GH')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR-GA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-CE')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-FH')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-CA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-LA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-AN')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'NE-MK')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TEC-CON')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'NE-FD')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-MO')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TEC-PL')->first()->id],

            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'BTC')->first()->id],

            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-S')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-CR')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'MI-MP')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-C4')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-C3')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'EE-SF')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-BD')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-RI')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TI-PA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR-GH')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TUR-GA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-CE')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-FH')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-CA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-LA')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'ALI-AN')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'NE-MK')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TEC-CON')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'NE-FD')->first()->id],
            ['sede_id' => Sede::where('codigo', 'S-LU')->first()->id, 'carrera_id' => Carrera::where('codigo', 'TEC-PL')->first()->id],

        ]);
    }
}
